### ISSUE TITLE
Lists only show 200 items

### ISSUE THREAD

**Issue by NielsLeenheer** [ThaDafinser/UserAgentParserComparison#10]
The HTML files contains all the results, but only 200 items are shown at a time. This happens because you use list.js, which by defaults only shows the 200 first items in a list.

See the documentation at:
http://www.listjs.com/docs/options

You can raise this by setting the `page` property to a higher number.

**Comment by ThaDafinser** [comment]
Thank you.

I already raised it to 1000 at some pages: view-source:http://thadafinser.github.io/UserAgentParserComparison/results/BrowscapPhp/grouped/browser.html

I need to introduce pagination with the next update, which will include your 1.000.000 useragent from whichbrowser.

Is that kind of viewing good, or do you think another kind of viewing would be better?

**Comment by mimmi20** [comment]
@ThaDafinser Is it possible to download the lists of `not found` useragents?

**Comment by ThaDafinser** [comment]
@mimmi20 not directly currently, since i the `sqlite` database with the results was too large for github.

Currently you only execute localy all steps up to step 5) https://github.com/ThaDafinser/UserAgentParserComparison#step-5-fill-the-sqlite-database

and then query the database directly with a sqlite viewer.

// side note due too the amount of the data the next version will proably need another database (i will may use Doctrine for it, so the database can be choosen)

**Comment by ThaDafinser** [comment]
Solved
