### ISSUE TITLE
Some strings are expected to have no result

### ISSUE THREAD

**Issue by NielsLeenheer** [ThaDafinser/UserAgentParserComparison#17]
Some strings in the testsuites are expected to have no results, but they still end up in the "Not detected" page. I would argue that this page should only show unexpected "no results", because otherwise would imply a potential problem that needs to be fixed.

For example this string from the Whootee testsuite:
http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/10/a6/10a6f31a-25d7-4e92-ab28-0683ba5c8108.html

I think any string from the browscaps testsuite that is a "Fake Browser" is also an basically an expected "no result":
http://thadafinser.github.io/UserAgentParserComparison/v4/user-agent-detail/ca/fd/cafd83c7-79e6-4184-9d66-fb5a73e5c020.html

**Comment by ThaDafinser** [comment]
The question is how i can detect them automatically as fake.
Since 30.000 user agents are a huge number and the amount is growing.

The first idea i have is, that i parse every user agent from the test suite with the abstraction layer of `UserAgentParser` (with the parser of the related test suite) and if i have a result, its treated as a valid user agent.

This would eliminate the example from Woothee above, but not the example from browscap

**Comment by NielsLeenheer** [comment]
> The first idea i have is, that i parse every user agent from the test suite with the abstraction layer of UserAgentParser (with the parser of the related test suite) and if i have a result, its treated as a valid user agent.

This sounds like a good idea to do.

And the example from browscap should be solved already by the solution for bug #18.

**Comment by ThaDafinser** [comment]
Merged #20
